Change to install eslint on local to match the scope plugin package installed (#35)
if they are installed in different scope, you get errors like below
```
Cannot find module 'eslint-config-airbnb-base'
Referenced from: /Projects/web-app/.eslintrc
Error: Cannot find module 'eslint-config-airbnb-base'
```
And install eslint-cli to access it just like globally installed
package.